import React, { useState } from 'react';
import { AlertTriangle, CalendarDays, FileCode2, Film, Play, Settings2 } from 'lucide-react';
import type { Account, QueueJob } from '../types';

type Tab = 'resumen' | 'prompt' | 'archivos' | 'logs';

export function QueueReferenceDetail({ job, accounts, onOpenPreview, onOpenCalendar }: { job?: QueueJob; accounts: Account[]; onOpenPreview: (job: QueueJob) => void; onOpenCalendar: () => void }) {
  const [tab, setTab] = useState<Tab>('resumen');
  const account = accounts.find((item) => item.id === job?.target_account || item.username === job?.target_account);
  const progress = job?.progress ?? (job?.status === 'published' ? 100 : 0);
  return <section className="ref-section ref-queue-detail"><header className="ref-section-head"><h2>Detalle del job</h2></header>{job ? <><div className="ref-queue-detail-title"><span><Settings2 size={28}/></span><div><strong>{job.id}</strong><small>{job.keyword}</small></div><em>{job.status.replaceAll('_',' ')}</em></div><nav className="ref-account-tabs" aria-label="Secciones del job">{(['resumen','prompt','archivos','logs'] as const).map((item) => <button key={item} className={tab === item ? 'active' : ''} onClick={() => setTab(item)}>{item === 'archivos' ? 'Archivos' : item[0].toUpperCase()+item.slice(1)}</button>)}</nav>{tab === 'resumen' && <div className="ref-queue-detail-body"><dl className="ref-dl"><dt>Keyword</dt><dd>{job.keyword}</dd><dt>Cuenta</dt><dd>@{account?.username || job.target_account}</dd><dt>Dispositivo</dt><dd>{account?.device_serial || '—'}</dd><dt>Creado</dt><dd>{job.created_at ? new Date(job.created_at).toLocaleString('es-ES') : '—'}</dd></dl><div className="ref-job-progress"><span>Progreso</span><div className="ref-progress"><i style={{width:`${Math.max(0,Math.min(100,progress))}%`}}/></div><strong>{progress}%</strong></div><dl className="ref-dl"><dt>Estado</dt><dd>{job.status.replaceAll('_',' ')}</dd><dt>Programado</dt><dd>{job.scheduled_ts ? new Date(typeof job.scheduled_ts === 'number' ? job.scheduled_ts*1000 : job.scheduled_ts).toLocaleString('es-ES') : '—'}</dd></dl>{job.status === 'awaiting_manual_upload' && <div className="ref-job-adb-warning"><AlertTriangle size={17}/><div><strong>Acción manual necesaria</strong><p>La publicación automática no se completó. Revisa el trabajo y el dispositivo.</p></div></div>}<div className="ref-queue-detail-actions"><button className="ref-primary" onClick={() => onOpenPreview(job)}><Play size={14}/> Revisar</button><button className="ref-secondary" onClick={onOpenCalendar}><CalendarDays size={14}/> Calendario</button></div></div>}{tab === 'prompt' && <div className="ref-queue-detail-body"><h3><FileCode2 size={15}/> Prompt y guion</h3><p>{job.keyword}</p><pre>{job.script || 'Aún no hay guion generado para este trabajo.'}</pre></div>}{tab === 'archivos' && <div className="ref-queue-detail-body"><h3><Film size={15}/> Archivos</h3><p>{job.video_path ? `Vídeo: ${job.video_path}` : 'No hay vídeo disponible.'}</p><button className="ref-blue-button" onClick={() => onOpenPreview(job)}>Abrir vista previa</button></div>}{tab === 'logs' && <div className="ref-queue-detail-body"><h3>Estado y errores</h3><p>{job.error || 'No hay errores asociados a este trabajo.'}</p></div>}</> : <p className="ref-empty">Selecciona un trabajo.</p>}</section>;
}
