import React, { useEffect, useMemo, useState } from 'react';
import {
  Activity, AlertTriangle, CalendarDays, Check, CheckCircle2, Clock3,
  Code2, FileCode2, GitBranch, Globe2, Layers3, Link2, List,
  Play, Plus, RefreshCw, Search, Send, Server, ShieldCheck,
  Smartphone, Sparkles, Users, Zap,
} from 'lucide-react';
import type { Account, ProxyItem, QueueJob, StackInfo, SystemStats } from '../types';

export type ReferenceView = 'cuentas' | 'cola' | 'proxies' | 'moneyprinter' | 'panda' | 'curl' | 'code' | 'versions';

type Props = {
  view: ReferenceView;
  accounts: Account[];
  queue: QueueJob[];
  proxies: ProxyItem[];
  stats: SystemStats;
  stack: StackInfo;
  deviceCount: number;
  onSelectAccount: (account: Account) => void;
  onAddAccount: (account: Partial<Account>) => void;
  onProcessNextJob: () => void;
  onOpenTool: (view: ReferenceView) => void;
  onOpenPreview: (job: QueueJob) => void;
  onOpenCalendar: () => void;
};

const labels: Record<ReferenceView, { title: string; description: string; action: string }> = {
  cuentas: { title: 'Cuentas', description: 'Gestiona tus cuentas de redes sociales, monitorea su estado y rendimiento.', action: 'Nueva cuenta' },
  cola: { title: 'Cola', description: 'Gestiona la cola de generación y publicación de contenido', action: 'Generar siguiente' },
  proxies: { title: 'Proxies', description: 'Gestión de proxies, rotación y monitoreo de salud', action: 'Añadir proxy' },
  moneyprinter: { title: 'MoneyPrinter', description: 'Genera, edita y publica contenido para todas tus cuentas', action: 'Crear contenido' },
  panda: { title: 'Panda Live', description: 'Monitoreo en tiempo real de dispositivos y sesiones', action: 'Abrir dispositivos' },
  curl: { title: 'cURL API', description: 'Explora y prueba la API de Phone Farm con solicitudes cURL', action: 'Abrir playground' },
  code: { title: 'Código Python', description: 'Desarrolla y ejecuta scripts para automatizar tareas en tu Phone Farm', action: 'Abrir editor' },
  versions: { title: 'Versiones', description: 'Control de versiones, despliegues y gestión de entornos', action: 'Ver versiones' },
};

const formatNumber = (n: number) => new Intl.NumberFormat('es-ES').format(n);
const readyStates = new Set<QueueJob['status']>(['awaiting_preview', 'ready_for_publish']);
const workingStates = new Set<QueueJob['status']>(['scripting', 'generating']);
const waitingStates = new Set<QueueJob['status']>(['pending', 'awaiting_approval']);
const badStates = new Set<QueueJob['status']>(['failed', 'rejected']);

function Metric({ label, value, detail, tone, icon }: { label: string; value: string | number; detail?: string; tone: 'blue' | 'green' | 'purple' | 'yellow' | 'red'; icon: React.ReactNode }) {
  return <div className={`ref-metric ref-tone-${tone}`}>
    <span className="ref-metric-icon">{icon}</span>
    <div className="ref-metric-copy"><span>{label}</span><strong>{value}</strong><small>{detail ?? 'Datos actuales'}</small></div>
    <div className="ref-metric-decoration" aria-hidden="true"><i/><i/><i/><i/><i/><i/></div>
  </div>;
}

function Section({ title, children, action, className = '' }: { title: string; children: React.ReactNode; action?: React.ReactNode; className?: string }) {
  return <section className={`ref-section ${className}`}><header className="ref-section-head"><h2>{title}</h2>{action}</header>{children}</section>;
}

function Status({ children, tone }: { children: React.ReactNode; tone: 'green' | 'blue' | 'yellow' | 'red' | 'purple' }) {
  return <span className={`ref-status ref-status-${tone}`}>{children}</span>;
}

export function ReferenceViews({ view, accounts, queue, proxies, stats, stack, deviceCount, onSelectAccount, onAddAccount, onProcessNextJob, onOpenTool, onOpenPreview, onOpenCalendar }: Props) {
  const [query, setQuery] = useState('');
  const [selectedJob, setSelectedJob] = useState<string | null>(null);
  const [selectedAccount, setSelectedAccount] = useState<string | null>(null);
  const [selectedProxy, setSelectedProxy] = useState<string | null>(null);
  const [accountFilter, setAccountFilter] = useState('all');
  const [showAccountForm, setShowAccountForm] = useState(false);
  const [newAccount, setNewAccount] = useState({ username: '', password: '', device_serial: '', proxy_id: '', warmup_day: 1 });
  useEffect(() => {
    if (!showAccountForm) return;
    const previous = document.activeElement;
    const dialog = document.querySelector<HTMLElement>('.ref-dialog');
    const controls = [...(dialog?.querySelectorAll<HTMLElement>('button,input,select') ?? [])];
    controls[1]?.focus();
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') setShowAccountForm(false);
      if (event.key !== 'Tab' || controls.length === 0) return;
      const first = controls[0], last = controls[controls.length - 1];
      if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); }
      else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); }
    };
    dialog?.addEventListener('keydown', onKeyDown);
    return () => {
      dialog?.removeEventListener('keydown', onKeyDown);
      if (previous instanceof HTMLElement) previous.focus();
    };
  }, [showAccountForm]);
  const heading = labels[view];
  const selectedQueueJob = queue.find(j => j.id === selectedJob) ?? queue[0];
  const selectedAccountItem = accounts.find(a => a.id === selectedAccount) ?? accounts[0];
  const selectedProxyItem = proxies.find(p => p.id === selectedProxy) ?? proxies[0];
  const filteredAccounts = useMemo(() => accounts.filter(a =>
    (accountFilter === 'all' || a.status === accountFilter) && `${a.username} ${a.niche ?? ''} ${a.device_serial}`.toLowerCase().includes(query.toLowerCase())
  ), [accounts, accountFilter, query]);
  const filteredJobs = useMemo(() => queue.filter(j => `${j.id} ${j.keyword} ${j.target_account}`.toLowerCase().includes(query.toLowerCase())), [queue, query]);
  const filteredProxies = useMemo(() => proxies.filter(p => `${p.id} ${p.provider} ${p.host}`.toLowerCase().includes(query.toLowerCase())), [proxies, query]);
  const count = (states: Set<QueueJob['status']>) => queue.filter(j => states.has(j.status)).length;
  const activeAccounts = accounts.filter(a => a.status === 'active').length;
  const onlineProxies = proxies.filter(p => p.status === 'online').length;
  const action = () => view === 'cuentas' ? setShowAccountForm(true) : view === 'cola' ? onProcessNextJob() : onOpenTool(view);

  return <div className={`ref-page ref-view-${view}`}>
    {showAccountForm && <div className="ref-dialog-backdrop" role="presentation" onMouseDown={e => e.target === e.currentTarget && setShowAccountForm(false)}><form className="ref-dialog" role="dialog" aria-modal="true" aria-label="Nueva cuenta" onSubmit={e => { e.preventDefault(); onAddAccount(newAccount); setShowAccountForm(false); setNewAccount({ username: '', password: '', device_serial: '', proxy_id: '', warmup_day: 1 }); }}><header><h2>Nueva cuenta</h2><button type="button" onClick={() => setShowAccountForm(false)} aria-label="Cerrar">×</button></header><label>Usuario<input required value={newAccount.username} onChange={e => setNewAccount({...newAccount,username:e.target.value})}/></label><label>Contraseña<input type="password" value={newAccount.password} onChange={e => setNewAccount({...newAccount,password:e.target.value})}/></label><label>Serial del dispositivo<input required value={newAccount.device_serial} onChange={e => setNewAccount({...newAccount,device_serial:e.target.value})}/></label><label>Proxy<select value={newAccount.proxy_id} onChange={e => setNewAccount({...newAccount,proxy_id:e.target.value})}><option value="">Sin proxy</option>{proxies.map(p => <option key={p.id} value={p.id}>{p.id}</option>)}</select></label><label>Día de warmup<input type="number" min="1" value={newAccount.warmup_day} onChange={e => setNewAccount({...newAccount,warmup_day:Number(e.target.value)})}/></label><button className="ref-primary" type="submit">Crear cuenta</button></form></div>}
    <div className="ref-page-heading"><div><h1>{heading.title}</h1><p>{heading.description}</p></div><button className="ref-primary" onClick={action}><Plus size={16}/>{heading.action}</button></div>

    {view === 'cuentas' && <>
      <div className="ref-metrics"><Metric label="Total de cuentas" value={formatNumber(accounts.length)} detail="Cuentas registradas" tone="blue" icon={<Users/>}/><Metric label="Cuentas activas" value={activeAccounts} detail={`${accounts.length ? Math.round(activeAccounts/accounts.length*100) : 0}% del total`} tone="green" icon={<CheckCircle2/>}/><Metric label="En riesgo" value={accounts.filter(a => a.status === 'warmup' || a.status === 'error').length} detail="Requieren atención" tone="yellow" icon={<AlertTriangle/>}/><Metric label="Suspendidas" value={accounts.filter(a => a.status === 'paused').length} detail="Cuentas pausadas" tone="red" icon={<Activity/>}/></div>
      <div className="ref-split ref-accounts-split"><Section title="Lista de cuentas" className="ref-table-section" action={<span>{filteredAccounts.length} cuentas</span>}>
        <div className="ref-filters"><select aria-label="Filtrar cuentas por estado" value={accountFilter} onChange={e => setAccountFilter(e.target.value)}><option value="all">Todos los estados</option><option value="active">Activas</option><option value="warmup">En riesgo</option><option value="paused">Pausadas</option><option value="error">Con errores</option></select><label className="ref-search"><Search size={15}/><input aria-label="Buscar cuentas" placeholder="Buscar cuentas, usuario o nicho..." value={query} onChange={e => setQuery(e.target.value)}/></label></div>
        <div className="ref-table-scroll"><table className="ref-table"><thead><tr><th>Plataforma</th><th>Usuario</th><th>Nicho</th><th>Dispositivo</th><th>Proxy</th><th>Salud</th><th>Posts hoy</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{filteredAccounts.map(a => <tr key={a.id} onClick={() => setSelectedAccount(a.id)} tabIndex={0} onKeyDown={e => e.key === 'Enter' && setSelectedAccount(a.id)}><td><span className="ref-platform">{a.platform === 'tiktok' ? '♪' : a.platform === 'both' ? '◎' : '◎'}</span></td><td><strong>@{a.username}</strong><small>{a.device_serial}</small></td><td>{a.niche || '—'}</td><td><span className="ref-dot"/>{a.device_serial || '—'}</td><td>{a.proxy_id || '—'}</td><td><div className="ref-health"><span>{a.status === 'active' ? '●' : '◐'}</span><i style={{ width: `${a.status === 'active' ? 85 : a.status === 'warmup' ? 55 : 15}%` }}/></div></td><td>{(a.likes_today ?? 0) + (a.follows_today ?? 0) + (a.comments_today ?? 0)}</td><td><Status tone={a.status === 'active' ? 'green' : a.status === 'paused' || a.status === 'error' ? 'red' : 'yellow'}>{a.status === 'active' ? 'Activa' : a.status === 'paused' ? 'Pausada' : a.status === 'warmup' ? 'En riesgo' : 'Error'}</Status></td><td><button className="ref-link" onClick={e => {e.stopPropagation(); onSelectAccount(a);}}>Ver</button></td></tr>)}</tbody></table>{filteredAccounts.length === 0 && <p className="ref-empty">No hay cuentas que coincidan con el filtro.</p>}</div>
      </Section><Section title={selectedAccountItem ? `@${selectedAccountItem.username}` : 'Detalle de cuenta'} className="ref-detail"><div className="ref-account-profile"><div className="ref-avatar"><Users size={32}/></div><div><strong>{selectedAccountItem ? `@${selectedAccountItem.username}` : 'Sin cuenta seleccionada'}</strong><p>{selectedAccountItem?.platform || '—'}</p></div></div><div className="ref-detail-grid"><div><strong>{formatNumber(selectedAccountItem?.followers_count ?? 0)}</strong><span>Seguidores</span></div><div><strong>{formatNumber(selectedAccountItem?.following_count ?? 0)}</strong><span>Siguiendo</span></div><div><strong>{formatNumber(selectedAccountItem?.posts_count ?? 0)}</strong><span>Publicaciones</span></div></div><button className="ref-blue-button" disabled={!selectedAccountItem} onClick={() => selectedAccountItem && onSelectAccount(selectedAccountItem)}>Abrir detalles</button><div className="ref-subsection"><h3>Actividad reciente</h3><p>{selectedAccountItem?.last_activity || 'Sin actividad reciente'}</p></div></Section></div>
    </>}

    {view === 'cola' && <>
      <div className="ref-metrics ref-five"><Metric label="En cola" value={count(waitingStates)} detail="Pendientes" tone="blue" icon={<List/>}/><Metric label="Generando" value={count(workingStates)} detail="En proceso" tone="purple" icon={<Sparkles/>}/><Metric label="Listo" value={count(readyStates)} detail="Para revisar" tone="green" icon={<CheckCircle2/>}/><Metric label="Publicando" value={queue.filter(j => j.status === 'publishing').length} detail="En curso" tone="blue" icon={<Send/>}/><Metric label="Errores" value={count(badStates)} detail="Requieren atención" tone="red" icon={<AlertTriangle/>}/></div>
      <Section title={`Pipeline de la cola (${queue.length} jobs)`}><div className="ref-pipeline">{[['En cola',count(waitingStates),'blue'],['Generando',count(workingStates),'purple'],['Listo',count(readyStates),'green'],['Publicando',queue.filter(j => j.status === 'publishing').length,'blue'],['Completado',queue.filter(j => j.status === 'published').length,'green'],['Errores',count(badStates),'red']].map(([name,num,tone]) => <div className={`ref-pipeline-step ref-tone-${tone}`} key={name}><strong>{name}</strong><b>{num}</b></div>)}</div></Section>
      <div className="ref-split ref-queue-split"><Section title={`Jobs en cola (${filteredJobs.length})`} className="ref-table-section"><div className="ref-filters"><label className="ref-search"><Search size={15}/><input aria-label="Buscar jobs" placeholder="keyword, cuenta o job..." value={query} onChange={e => setQuery(e.target.value)}/></label><button onClick={onOpenCalendar} className="ref-secondary"><CalendarDays size={15}/> Calendario</button></div><div className="ref-table-scroll"><table className="ref-table"><thead><tr><th>Job</th><th>Keyword</th><th>Cuenta</th><th>Progreso</th><th>Estado</th><th>Creado</th><th>Acciones</th></tr></thead><tbody>{filteredJobs.map(j => <tr key={j.id} className={selectedQueueJob?.id === j.id ? 'ref-selected' : ''} onClick={() => setSelectedJob(j.id)}><td>{j.id}</td><td><strong>{j.keyword}</strong></td><td>@{j.target_account}</td><td><div className="ref-progress"><i style={{ width: `${j.progress ?? (j.status === 'published' ? 100 : 0)}%` }}/></div></td><td><Status tone={badStates.has(j.status) ? 'red' : workingStates.has(j.status) ? 'purple' : j.status === 'published' ? 'green' : 'blue'}>{j.status}</Status></td><td>{j.created_at ? new Date(j.created_at).toLocaleDateString('es-ES') : '—'}</td><td><button className="ref-link" onClick={e => {e.stopPropagation(); onOpenPreview(j);}}>Ver</button></td></tr>)}</tbody></table>{filteredJobs.length === 0 && <p className="ref-empty">No hay jobs que coincidan con la búsqueda.</p>}</div></Section><Section title="Detalle del job" className="ref-detail">{selectedQueueJob ? <><div className="ref-job-title"><span className="ref-metric-icon ref-tone-purple"><Sparkles/></span><div><strong>{selectedQueueJob.id}</strong><p>{selectedQueueJob.keyword}</p></div></div><dl className="ref-dl"><dt>Cuenta</dt><dd>@{selectedQueueJob.target_account}</dd><dt>Estado</dt><dd>{selectedQueueJob.status}</dd><dt>Progreso</dt><dd>{selectedQueueJob.progress ?? 0}%</dd><dt>Creado</dt><dd>{selectedQueueJob.created_at}</dd></dl><button className="ref-blue-button" onClick={() => onOpenPreview(selectedQueueJob)}><Play size={15}/> Ver trabajo</button></> : <p className="ref-empty">Selecciona un job.</p>}</Section></div>
    </>}

    {view === 'proxies' && <>
      <div className="ref-metrics"><Metric label="Proxies activos" value={`${onlineProxies} / ${proxies.length}`} detail="Operativos" tone="blue" icon={<Link2/>}/><Metric label="Proxies inestables" value={proxies.filter(p => p.status !== 'online').length} detail="Requieren revisión" tone="red" icon={<AlertTriangle/>}/><Metric label="Rotación media" value="—" detail="Sin telemetría" tone="blue" icon={<RefreshCw/>}/><Metric label="Latencia media" value={onlineProxies ? `${Math.round(proxies.filter(p => p.status === 'online').reduce((n,p) => n+(p.latency_ms ?? 0),0)/onlineProxies)} ms` : '—'} detail="Proxies en línea" tone="purple" icon={<Clock3/>}/></div>
      <div className="ref-split ref-proxy-split"><div className="ref-stack"><div className="ref-two"><Section title="Latencia promedio"><div className="ref-chart-placeholder"><Activity size={28}/><span>Telemetría de latencia no disponible</span></div></Section><Section title="Tasa de errores"><div className="ref-chart-placeholder"><Activity size={28}/><span>Telemetría de errores no disponible</span></div></Section></div><Section title={`Lista de proxies (${filteredProxies.length})`} className="ref-table-section"><div className="ref-filters"><label className="ref-search"><Search size={15}/><input aria-label="Buscar proxies" placeholder="Buscar proxy, IP o proveedor..." value={query} onChange={e => setQuery(e.target.value)}/></label></div><div className="ref-table-scroll"><table className="ref-table"><thead><tr><th>Alias</th><th>Proveedor</th><th>IP</th><th>Cuenta</th><th>Latencia</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{filteredProxies.map(p => <tr key={p.id} className={selectedProxyItem?.id === p.id ? 'ref-selected' : ''} onClick={() => setSelectedProxy(p.id)}><td><span className="ref-dot"/>{p.id}</td><td>{p.provider || '—'}</td><td>{p.ip || p.host}</td><td>{p.assigned_account || '—'}</td><td>{p.latency_ms == null ? '—' : `${p.latency_ms} ms`}</td><td><Status tone={p.status === 'online' ? 'green' : p.status === 'checking' ? 'yellow' : 'red'}>{p.status === 'online' ? 'Activa' : p.status === 'checking' ? 'Probando' : 'Offline'}</Status></td><td><button className="ref-link" onClick={e => {e.stopPropagation(); onOpenTool('proxies');}}>Gestionar</button></td></tr>)}</tbody></table>{filteredProxies.length === 0 && <p className="ref-empty">No hay proxies que coincidan con la búsqueda.</p>}</div></Section></div><Section title="Configuración y acciones" className="ref-detail"><div className="ref-subsection"><h3><RefreshCw size={16}/> Reglas de rotación</h3><p>Gestiona la rotación desde la configuración de proxies.</p><button className="ref-blue-button" onClick={() => onOpenTool('proxies')}>Abrir configuración</button></div><div className="ref-subsection"><h3><ShieldCheck size={16}/> Proxy seleccionado</h3>{selectedProxyItem ? <dl className="ref-dl"><dt>Proveedor</dt><dd>{selectedProxyItem.provider}</dd><dt>IP real</dt><dd>{selectedProxyItem.ip || selectedProxyItem.host}</dd><dt>Latencia</dt><dd>{selectedProxyItem.latency_ms ?? '—'} ms</dd><dt>Estado</dt><dd>{selectedProxyItem.status}</dd></dl> : <p>Sin proxy seleccionado</p>}</div></Section></div>
    </>}

    {view === 'moneyprinter' && <><div className="ref-metrics"><Metric label="Borradores generados" value={stack.drafts} tone="blue" icon={<FileCode2/>}/><Metric label="Trabajos aprobados" value={count(readyStates)} tone="green" icon={<CheckCircle2/>}/><Metric label="Vídeos listos" value={queue.filter(j => !!j.video_path).length} tone="purple" icon={<Play/>}/><Metric label="Errores" value={count(badStates)} tone="yellow" icon={<AlertTriangle/>}/></div><div className="ref-split ref-work-split"><Section title="Plantillas y lotes" className="ref-detail"><div className="ref-tabs"><button className="active">Plantillas</button><button onClick={() => onOpenTool('moneyprinter')}>Workflows</button></div><button className="ref-blue-button" onClick={() => onOpenTool('moneyprinter')}><Plus size={15}/> Nueva generación</button><div className="ref-subsection"><h3>Lotes de contenido</h3>{queue.slice(0,5).map(j => <div className="ref-list-row" key={j.id}><span>{j.keyword}</span><Status tone={badStates.has(j.status) ? 'red' : 'blue'}>{j.status}</Status></div>)}</div></Section><Section title="Creador de contenido" className="ref-work-main" action={<button className="ref-primary" onClick={() => onOpenTool('moneyprinter')}><Sparkles size={15}/> Generar</button>}><div className="ref-form-grid"><div><label>Nicho / temática</label><div className="ref-field">{accounts[0]?.niche || 'Selecciona una cuenta'}</div></div><div><label>Objetivo</label><div className="ref-field">Generación de vídeo</div></div><div><label>Idioma</label><div className="ref-field">Español</div></div></div><div className="ref-subsection"><h3>Prompt del contenido</h3><p>Abre el creador para configurar el guion, la voz, el formato y los recursos visuales.</p><button className="ref-blue-button" onClick={() => onOpenTool('moneyprinter')}>Editar contenido</button></div></Section><Section title="Estado de generación" className="ref-detail"><div className="ref-list-row"><Check size={16}/> Flask <Status tone={stack.flask_online ? 'green' : 'red'}>{stack.flask_online ? 'Online' : 'Offline'}</Status></div><div className="ref-list-row"><Check size={16}/> MoneyPrinter <Status tone={stack.mpt_online ? 'green' : 'red'}>{stack.mpt_online ? 'Online' : 'Offline'}</Status></div><div className="ref-subsection"><h3>Salidas recientes</h3>{queue.filter(j => !!j.video_path).slice(0,3).map(j => <div className="ref-list-row" key={j.id}>{j.keyword}</div>)}</div></Section></div></>}

    {view === 'panda' && <><div className="ref-metrics"><Metric label="Dispositivos en vivo" value={`${deviceCount} / ${deviceCount}`} tone="blue" icon={<Smartphone/>}/><Metric label="Sesiones activas" value={stats.active_bots} tone="green" icon={<Users/>}/><Metric label="Leases en uso" value="—" detail="Sin dato del servidor" tone="purple" icon={<Layers3/>}/><Metric label="Operadores conectados" value="—" detail="Sin dato del servidor" tone="blue" icon={<Users/>}/></div><div className="ref-device-grid">{accounts.slice(0,4).map(a => <Section key={a.id} title={`@${a.username}`}><div className="ref-phone"><Smartphone size={52}/><p>Vista en vivo disponible en Panda</p><button className="ref-blue-button" onClick={() => onOpenTool('panda')}>Abrir dispositivo</button></div><div className="ref-list-row"><span className="ref-dot"/>{a.device_serial}</div></Section>)}{accounts.length === 0 && <Section title="Dispositivos"><p className="ref-empty">No hay cuentas con dispositivos registrados.</p></Section>}</div><Section title="Eventos en tiempo real"><p className="ref-empty">Abre Panda Live para ver el estado y las sesiones en tiempo real.</p></Section></>}

    {view === 'curl' && <><div className="ref-metrics"><Metric label="Endpoints disponibles" value="—" detail="Contrato OpenAPI" tone="blue" icon={<FileCode2/>}/><Metric label="Solicitudes hoy" value="—" detail="Sin contador diario" tone="green" icon={<Send/>}/><Metric label="Errores (4xx/5xx)" value={stats.errores} tone="red" icon={<AlertTriangle/>}/><Metric label="Latencia media" value="—" detail="Sin telemetría" tone="purple" icon={<Clock3/>}/></div><div className="ref-tabs ref-large-tabs"><button onClick={() => onOpenTool('curl')}>Docs</button><button className="active" onClick={() => onOpenTool('curl')}>Playground</button><button onClick={() => onOpenTool('curl')}>Logs</button></div><div className="ref-split ref-api-split"><Section title="Endpoints"><label className="ref-search"><Search size={15}/><input aria-label="Buscar endpoints" placeholder="Buscar endpoints..." value={query} onChange={e => setQuery(e.target.value)}/></label><div className="ref-subsection"><h3>Dispositivos</h3>{['Listar dispositivos','Obtener dispositivo','Reiniciar dispositivo','Ejecutar comando ADB'].filter(x => x.toLowerCase().includes(query.toLowerCase())).map(x => <button className="ref-endpoint" key={x} onClick={() => onOpenTool('curl')}><Status tone="green">GET</Status>{x}</button>)}</div></Section><Section title="Listar dispositivos" className="ref-work-main"><div className="ref-endpoint-title"><Status tone="green">GET</Status><code>/api/devices</code></div><p className="ref-muted">Obtiene la lista de todos los dispositivos registrados en la granja.</p><div className="ref-subsection"><h3>Solicitud</h3><div className="ref-field">GET　/api/devices</div><button className="ref-blue-button" onClick={() => onOpenTool('curl')}><Play size={15}/> Enviar solicitud</button></div></Section><Section title="Respuesta" className="ref-detail"><Status tone="blue">Abre el playground</Status><pre className="ref-code">{JSON.stringify({ devices: deviceCount, status: stack.flask_online ? 'online' : 'offline' }, null, 2)}</pre></Section></div></>}

    {view === 'code' && <><div className="ref-metrics"><Metric label="Scripts activos" value="—" detail="Repositorio Python" tone="blue" icon={<FileCode2/>}/><Metric label="Ejecuciones hoy" value="—" detail="Sin contador diario" tone="purple" icon={<Play/>}/><Metric label="Errores" value={stats.errores} tone="red" icon={<AlertTriangle/>}/><Metric label="Workers Python" value="—" detail="Sin telemetría" tone="green" icon={<Users/>}/></div><div className="ref-split ref-code-split"><Section title="Archivos"><label className="ref-search"><Search size={15}/><input aria-label="Buscar archivos" placeholder="Buscar archivos..."/></label><button className="ref-endpoint" onClick={() => onOpenTool('code')}><FileCode2 size={17}/> Abrir explorador de archivos</button></Section><Section title="Editor Python" className="ref-work-main"><div className="ref-editor-placeholder"><Code2 size={36}/><p>El editor carga los archivos reales del backend.</p><button className="ref-blue-button" onClick={() => onOpenTool('code')}>Abrir código</button></div></Section><Section title="Ejecución" className="ref-detail"><p className="ref-muted">Selecciona un script y un dispositivo para ejecutar una tarea.</p><button className="ref-blue-button" onClick={() => onOpenTool('code')}><Play size={15}/> Abrir editor</button></Section></div></>}

    {view === 'versions' && <><div className="ref-metrics"><Metric label="Versión actual" value={stack.package_version || '—'} detail="Panel" tone="blue" icon={<Layers3/>}/><Metric label="Despliegues este mes" value="—" detail="Sin historial de despliegue" tone="green" icon={<Zap/>}/><Metric label="Entornos activos" value={stack.containers.length} detail="Contenedores" tone="purple" icon={<Server/>}/><Metric label="Incidentes" value={stats.errores} tone="red" icon={<AlertTriangle/>}/></div><div className="ref-split ref-version-split"><div className="ref-stack"><Section title="Entornos de despliegue"><div className="ref-environments">{stack.containers.length ? stack.containers.map(c => <div className="ref-environment" key={c.name}><Globe2 size={24}/><strong>{c.name}</strong><Status tone={c.status.toLowerCase().includes('up') ? 'green' : 'yellow'}>{c.status}</Status><small>{c.ports}</small></div>) : <p className="ref-empty">No hay contenedores registrados.</p>}</div></Section><Section title="Historial de versiones"><div className="ref-version-row"><GitBranch size={19}/><strong>{stack.package_version || '—'}</strong><Status tone="green">Actual</Status><span>{stack.git_sha || 'Sin SHA disponible'}</span></div><div className="ref-version-row"><GitBranch size={19}/><strong>{stack.mpt_pinned_version || '—'}</strong><Status tone="blue">MPT</Status><span>{stack.mpt_pinned_sha || 'Sin SHA disponible'}</span></div></Section></div><Section title="Detalles del despliegue" className="ref-detail"><div className="ref-job-title"><span className="ref-metric-icon ref-tone-blue"><Layers3/></span><div><strong>{stack.package_version || '—'}</strong><p>{stack.git_sha || 'Sin revisión disponible'}</p></div></div><dl className="ref-dl"><dt>Flask</dt><dd>{stack.flask_online ? 'Online' : 'Offline'}</dd><dt>MoneyPrinter</dt><dd>{stack.mpt_online ? 'Online' : 'Offline'}</dd><dt>Modo</dt><dd>{stack.mode || '—'}</dd></dl><button className="ref-blue-button" onClick={() => onOpenTool('versions')}>Ver detalles</button></Section></div></>}
  </div>;
}
